// unit3_mcq.js
// Analytical Skills-II
// Unit 3: Time, Speed and Distance
// 15 Self-Assessment Based + 20 Concept MCQs + 10 Tricky Exam MCQs

const analyticalUnit3MCQs = [
  // =========================
  // 15 SELF-ASSESSMENT BASED
  // =========================
  {
    id: "AS-U3-SA-01",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Average Speed",
    question: "A boy goes to school at 6 km/hr and returns at 3 km/hr. If he takes 5 hours in all, find the distance between home and school.",
    options: ["5 km", "6 km", "10 km", "12 km"],
    answer: "C",
    correctAnswer: "10 km",
    solution: "Let one-side distance be D. Time taken = D/6 + D/3 = 5. So D/6 + 2D/6 = 5, 3D/6 = 5, D/2 = 5, therefore D = 10 km.",
    shortcut: "For same distance, use: Total time = D/s1 + D/s2."
  },
  {
    id: "AS-U3-SA-02",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Late and Early",
    question: "Walking at 4 km/hr, a clerk reaches office 5 minutes late. Walking at 5 km/hr, he reaches 2.5 minutes early. Find the distance.",
    options: ["15 km", "10 km", "25 km", "2.5 km"],
    answer: "D",
    correctAnswer: "2.5 km",
    solution: "Difference in time = 5 + 2.5 = 7.5 minutes = 1/8 hour. Let distance be D. D/4 - D/5 = 1/8. So D/20 = 1/8, therefore D = 20/8 = 2.5 km.",
    shortcut: "Distance = Time difference / difference of reciprocal speeds."
  },
  {
    id: "AS-U3-SA-03",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Time and Speed Ratio",
    question: "To cover the same distance, time taken by two trains is in the ratio 5:7. If the second train runs 400 km in 4 hours, what is the speed of the first train?",
    options: ["85 km/hr", "140 km/hr", "90 km/hr", "120 km/hr"],
    answer: "B",
    correctAnswer: "140 km/hr",
    solution: "Speed of second train = 400/4 = 100 km/hr. For same distance, speed ratio is inverse of time ratio. Time ratio = 5:7, so speed ratio = 7:5. First train speed = 100 × 7/5 = 140 km/hr.",
    shortcut: "Same distance: Speed ratio = inverse of time ratio."
  },
  {
    id: "AS-U3-SA-04",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Reduced Speed",
    question: "By walking at 3/7 of his usual speed, a man reaches office 20 minutes late. What is his usual travel time?",
    options: ["10 minutes", "15 minutes", "20 minutes", "25 minutes"],
    answer: "B",
    correctAnswer: "15 minutes",
    solution: "Speed ratio new:usual = 3:7. Time ratio new:usual = 7:3. Difference = 4 parts = 20 minutes. So 1 part = 5 minutes. Usual time = 3 parts = 15 minutes.",
    shortcut: "If speed becomes a/b of usual, time becomes b/a of usual."
  },
  {
    id: "AS-U3-SA-05",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Train Meeting",
    question: "A train leaves Delhi at 6 AM and reaches Agra at 10 AM. Another train leaves Agra at 8 AM and reaches Delhi at 11:30 AM. At what time will the trains cross each other?",
    options: ["8:32 AM", "8:48 AM", "8:52 AM", "8:56 AM"],
    answer: "D",
    correctAnswer: "8:56 AM",
    solution: "Let distance be D. First train speed = D/4. Second train speed = D/3.5 = 2D/7. By 8 AM, first train has travelled D/2. Remaining distance = D/2. Relative speed = D/4 + 2D/7 = 15D/28. Time after 8 AM = (D/2)/(15D/28) = 14/15 hour = 56 minutes.",
    shortcut: "When trains move towards each other, relative speed = sum of speeds."
  },
  {
    id: "AS-U3-SA-06",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Stoppage",
    question: "Without stoppage, a person travels at 80 km/hr. With stoppage, he covers the same distance at 60 km/hr. How many minutes per hour does he stop?",
    options: ["45 minutes", "30 minutes", "20 minutes", "15 minutes"],
    answer: "D",
    correctAnswer: "15 minutes",
    solution: "In 1 hour with stoppage, distance covered = 60 km. Time needed to cover 60 km at 80 km/hr = 60/80 = 3/4 hour = 45 minutes. Stop time = 60 - 45 = 15 minutes.",
    shortcut: "Stoppage per hour = 60 × (1 - speed with stop/speed without stop)."
  },
  {
    id: "AS-U3-SA-07",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Delayed Start Meeting",
    question: "Distance between stations A and B is 208 km. A train starts from A at 10 AM at 30 km/hr. Another train starts from B at 1:20 PM at 24 km/hr. When will they meet and how far from A?",
    options: ["2:20 PM, 120 km", "3:20 PM, 160 km", "2:20 PM, 160 km", "3:20 PM, 120 km"],
    answer: "B",
    correctAnswer: "3:20 PM, 160 km",
    solution: "From 10 AM to 1:20 PM = 3 hours 20 minutes = 10/3 hours. First train covers 30 × 10/3 = 100 km. Remaining distance = 208 - 100 = 108 km. Relative speed = 30 + 24 = 54 km/hr. Time after 1:20 PM = 108/54 = 2 hours. Meeting time = 3:20 PM. Distance from A = 100 + 30×2 = 160 km.",
    shortcut: "First find distance covered before the second train starts."
  },
  {
    id: "AS-U3-SA-08",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Police and Thief",
    question: "A thief is noticed by a policeman from 200 m. The thief and policeman run at 10 km/hr and 11 km/hr respectively. What is the distance between them after 6 minutes?",
    options: ["100 m", "190 m", "200 m", "150 m"],
    answer: "A",
    correctAnswer: "100 m",
    solution: "Relative speed = 11 - 10 = 1 km/hr. In 6 minutes = 1/10 hour, policeman gains 1 × 1/10 = 0.1 km = 100 m. Initial gap = 200 m. Remaining gap = 200 - 100 = 100 m.",
    shortcut: "Distance reduced = relative speed × time."
  },
  {
    id: "AS-U3-SA-09",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Average Speed",
    question: "A man goes by car at 30 km/hr and returns to the starting point at 40 km/hr. Find the average speed for the whole journey.",
    options: ["35 km/hr", "34.3 km/hr", "36 km/hr", "None"],
    answer: "B",
    correctAnswer: "34.3 km/hr",
    solution: "For equal distance, average speed = 2xy/(x+y) = 2×30×40/(30+40) = 2400/70 = 34.3 km/hr.",
    shortcut: "Equal distance average speed = 2ab/(a+b)."
  },
  {
    id: "AS-U3-SA-10",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Fractional Journey",
    question: "A man covers 1/4 of his journey at 20 km/hr and the remaining at 30 km/hr. He takes 15 hours in total. Find the total distance.",
    options: ["400 km", "300 km", "390 km", "None"],
    answer: "A",
    correctAnswer: "400 km",
    solution: "Let total distance be D. Time = (D/4)/20 + (3D/4)/30 = D/80 + D/40 = 3D/80. Given 3D/80 = 15, so D = 400 km.",
    shortcut: "Break journey into fractions, then use time = distance/speed."
  },
  {
    id: "AS-U3-SA-11",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Same Time Different Speed",
    question: "If a person walks at 14 km/hr instead of 10 km/hr, he would have walked 20 km more. Find the actual distance travelled.",
    options: ["50 km", "56 km", "70 km", "80 km"],
    answer: "A",
    correctAnswer: "50 km",
    solution: "Let time be t hours. Difference in distance = (14 - 10)t = 20. So 4t = 20, t = 5 hours. Actual distance = 10 × 5 = 50 km.",
    shortcut: "Extra distance = difference in speed × time."
  },
  {
    id: "AS-U3-SA-12",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Flight Speed",
    question: "In a flight of 600 km, an aircraft was slowed due to bad weather. Its average speed was reduced by 200 km/hr and time increased by 30 minutes. Find the original duration of flight.",
    options: ["1 hour", "2 hours", "3 hours", "4 hours"],
    answer: "A",
    correctAnswer: "1 hour",
    solution: "Let original speed be x. Then 600/(x-200) - 600/x = 1/2. Solving gives x = 600 km/hr. Original time = 600/600 = 1 hour.",
    shortcut: "Use time difference: D/(reduced speed) - D/(original speed)."
  },
  {
    id: "AS-U3-SA-13",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Two Modes",
    question: "A man travelled 61 km in 9 hours. He travelled partly on foot at 4 km/hr and partly on bicycle at 9 km/hr. Find the distance travelled on foot.",
    options: ["16 km", "14 km", "12 km", "10 km"],
    answer: "A",
    correctAnswer: "16 km",
    solution: "Let walking distance be x. Then x/4 + (61-x)/9 = 9. Multiplying by 36: 9x + 4(61-x) = 324. So 9x + 244 - 4x = 324, 5x = 80, x = 16 km.",
    shortcut: "For two modes, let one distance be x and use total time."
  },
  {
    id: "AS-U3-SA-14",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Train with Stops",
    question: "An express train travels at 100 km/hr and stops for 3 minutes after every 75 km. How much time will it take to travel 600 km?",
    options: ["6 hours 21 minutes", "6 hours 24 minutes", "6 hours 27 minutes", "6 hours 30 minutes"],
    answer: "A",
    correctAnswer: "6 hours 21 minutes",
    solution: "Running time = 600/100 = 6 hours. Stops occur after 75, 150, 225, 300, 375, 450 and 525 km, so 7 stops. Total stoppage = 7×3 = 21 minutes. Total time = 6 hours 21 minutes.",
    shortcut: "Do not count a stop after reaching the destination."
  },
  {
    id: "AS-U3-SA-15",
    unit: 3,
    category: "Self-Assessment Based",
    topic: "Accident Speed Reduction",
    question: "A train after running 100 km meets with an accident and then runs at 3/5 of its former speed, reaching 48 minutes late. If the accident had happened 30 km further, it would be late by 24 minutes. Find the original speed.",
    options: ["125 km/hr", "150 km/hr", "100 km/hr", "50 km/hr"],
    answer: "D",
    correctAnswer: "50 km/hr",
    solution: "Accident 30 km further reduces delay by 24 minutes = 0.4 hour. Let original speed be S. Reduced speed = 3S/5. Extra time for 30 km = 30/(3S/5) - 30/S = 50/S - 30/S = 20/S. So 20/S = 0.4, S = 50 km/hr.",
    shortcut: "Delay difference comes only from the extra 30 km covered at normal speed."
  },

  // =================
  // 20 CONCEPT MCQs
  // =================
  {
    id: "AS-U3-C-16",
    unit: 3,
    category: "Concept MCQ",
    topic: "Distance Formula",
    question: "A car travels at 60 km/hr for 2.5 hours. What distance does it cover?",
    options: ["120 km", "140 km", "150 km", "180 km"],
    answer: "C",
    correctAnswer: "150 km",
    solution: "Distance = Speed × Time = 60 × 2.5 = 150 km.",
    shortcut: "D = S × T."
  },
  {
    id: "AS-U3-C-17",
    unit: 3,
    category: "Concept MCQ",
    topic: "Time Formula",
    question: "How much time is required to cover 180 km at 45 km/hr?",
    options: ["3 hours", "4 hours", "5 hours", "6 hours"],
    answer: "B",
    correctAnswer: "4 hours",
    solution: "Time = Distance / Speed = 180/45 = 4 hours.",
    shortcut: "T = D/S."
  },
  {
    id: "AS-U3-C-18",
    unit: 3,
    category: "Concept MCQ",
    topic: "Unit Conversion",
    question: "Convert 72 km/hr into m/s.",
    options: ["10 m/s", "15 m/s", "20 m/s", "25 m/s"],
    answer: "C",
    correctAnswer: "20 m/s",
    solution: "72 km/hr = 72 × 5/18 = 20 m/s.",
    shortcut: "km/hr to m/s: multiply by 5/18."
  },
  {
    id: "AS-U3-C-19",
    unit: 3,
    category: "Concept MCQ",
    topic: "Unit Conversion",
    question: "Convert 15 m/s into km/hr.",
    options: ["36 km/hr", "45 km/hr", "54 km/hr", "60 km/hr"],
    answer: "C",
    correctAnswer: "54 km/hr",
    solution: "15 m/s = 15 × 18/5 = 54 km/hr.",
    shortcut: "m/s to km/hr: multiply by 18/5."
  },
  {
    id: "AS-U3-C-20",
    unit: 3,
    category: "Concept MCQ",
    topic: "Average Speed",
    question: "A person goes from A to B at 40 km/hr and returns at 60 km/hr. Find the average speed.",
    options: ["45 km/hr", "48 km/hr", "50 km/hr", "52 km/hr"],
    answer: "B",
    correctAnswer: "48 km/hr",
    solution: "For equal distance, average speed = 2ab/(a+b) = 2×40×60/(40+60) = 4800/100 = 48 km/hr.",
    shortcut: "Equal distance average speed = 2ab/(a+b)."
  },
  {
    id: "AS-U3-C-21",
    unit: 3,
    category: "Concept MCQ",
    topic: "Average Speed",
    question: "A person travels for equal time at 40 km/hr and 60 km/hr. Find the average speed.",
    options: ["45 km/hr", "48 km/hr", "50 km/hr", "55 km/hr"],
    answer: "C",
    correctAnswer: "50 km/hr",
    solution: "When time is equal, average speed = (40 + 60)/2 = 50 km/hr.",
    shortcut: "Equal time average speed = (a+b)/2."
  },
  {
    id: "AS-U3-C-22",
    unit: 3,
    category: "Concept MCQ",
    topic: "Speed-Time Ratio",
    question: "Two persons cover the same distance. Their times are in the ratio 4:5. If the first person's speed is 50 km/hr, what is the second person's speed?",
    options: ["35 km/hr", "40 km/hr", "45 km/hr", "60 km/hr"],
    answer: "B",
    correctAnswer: "40 km/hr",
    solution: "For same distance, speed ratio is inverse of time ratio. Speed ratio = 5:4. First speed = 50, so second speed = 50×4/5 = 40 km/hr.",
    shortcut: "Same distance: S1:S2 = T2:T1."
  },
  {
    id: "AS-U3-C-23",
    unit: 3,
    category: "Concept MCQ",
    topic: "Relative Speed",
    question: "Two cars start from opposite ends of a 240 km road and move towards each other at 50 km/hr and 70 km/hr. When will they meet?",
    options: ["1 hour", "2 hours", "3 hours", "4 hours"],
    answer: "B",
    correctAnswer: "2 hours",
    solution: "Relative speed = 50 + 70 = 120 km/hr. Time = 240/120 = 2 hours.",
    shortcut: "Opposite direction relative speed = sum of speeds."
  },
  {
    id: "AS-U3-C-24",
    unit: 3,
    category: "Concept MCQ",
    topic: "Chase",
    question: "A car is 30 km ahead of another car. The first car moves at 45 km/hr and the second at 60 km/hr in the same direction. In how many hours will the second car catch the first?",
    options: ["1 hour", "2 hours", "3 hours", "4 hours"],
    answer: "B",
    correctAnswer: "2 hours",
    solution: "Relative speed = 60 - 45 = 15 km/hr. Time = gap/relative speed = 30/15 = 2 hours.",
    shortcut: "Same direction relative speed = difference of speeds."
  },
  {
    id: "AS-U3-C-25",
    unit: 3,
    category: "Concept MCQ",
    topic: "Stoppage",
    question: "Without stoppage, a bus travels at 54 km/hr. Including stoppages, its speed is 45 km/hr. How many minutes does it stop per hour?",
    options: ["5 minutes", "10 minutes", "12 minutes", "15 minutes"],
    answer: "B",
    correctAnswer: "10 minutes",
    solution: "In 1 hour including stoppage, distance = 45 km. Time needed to cover 45 km at 54 km/hr = 45/54 hour = 5/6 hour = 50 minutes. Stop time = 60 - 50 = 10 minutes.",
    shortcut: "Stop time per hour = 60 × (1 - actual speed/running speed)."
  },
  {
    id: "AS-U3-C-26",
    unit: 3,
    category: "Concept MCQ",
    topic: "Late and Early",
    question: "A student walks at 5 km/hr and reaches 10 minutes late. If he walks at 6 km/hr, he reaches 5 minutes early. Find the distance.",
    options: ["5 km", "6 km", "7.5 km", "10 km"],
    answer: "C",
    correctAnswer: "7.5 km",
    solution: "Time difference = 10 + 5 = 15 minutes = 1/4 hour. Let distance be D. D/5 - D/6 = 1/4. So D/30 = 1/4, D = 7.5 km.",
    shortcut: "Distance = time difference ÷ reciprocal-speed difference."
  },
  {
    id: "AS-U3-C-27",
    unit: 3,
    category: "Concept MCQ",
    topic: "Reduced Speed",
    question: "Walking at 4/5 of his usual speed, a man reaches 12 minutes late. Find his usual time.",
    options: ["36 minutes", "40 minutes", "48 minutes", "60 minutes"],
    answer: "C",
    correctAnswer: "48 minutes",
    solution: "Speed ratio new:usual = 4:5. Time ratio new:usual = 5:4. Difference = 1 part = 12 minutes. Usual time = 4 parts = 48 minutes.",
    shortcut: "Reduced speed increases time in inverse ratio."
  },
  {
    id: "AS-U3-C-28",
    unit: 3,
    category: "Concept MCQ",
    topic: "Train Meeting",
    question: "Distance between two cities is 330 km. A train starts from A at 8 AM at 60 km/hr. Another starts from B at 9 AM at 75 km/hr. At what time will they meet?",
    options: ["10 AM", "11 AM", "12 PM", "1 PM"],
    answer: "B",
    correctAnswer: "11 AM",
    solution: "First train travels for 1 hour before second starts, covering 60 km. Remaining distance = 330 - 60 = 270 km. Relative speed = 60 + 75 = 135 km/hr. Time after 9 AM = 270/135 = 2 hours. Meeting time = 11 AM.",
    shortcut: "For delayed start, subtract distance already covered first."
  },
  {
    id: "AS-U3-C-29",
    unit: 3,
    category: "Concept MCQ",
    topic: "Average Speed",
    question: "A man travels 20 km at 10 km/hr, 30 km at 15 km/hr and 50 km at 25 km/hr. Find his average speed.",
    options: ["15 km/hr", "16.67 km/hr", "18 km/hr", "20 km/hr"],
    answer: "B",
    correctAnswer: "16.67 km/hr",
    solution: "Total distance = 20 + 30 + 50 = 100 km. Total time = 20/10 + 30/15 + 50/25 = 2 + 2 + 2 = 6 hours. Average speed = 100/6 = 16.67 km/hr.",
    shortcut: "Average speed = total distance / total time."
  },
  {
    id: "AS-U3-C-30",
    unit: 3,
    category: "Concept MCQ",
    topic: "Percentage Speed Change",
    question: "If speed is increased by 25%, then time taken for the same distance is reduced by:",
    options: ["10%", "15%", "20%", "25%"],
    answer: "C",
    correctAnswer: "20%",
    solution: "New speed = 125% = 5/4 of old speed. Time becomes 4/5 of old time. Reduction = 1/5 = 20%.",
    shortcut: "For same distance, time is inversely proportional to speed."
  },
  {
    id: "AS-U3-C-31",
    unit: 3,
    category: "Concept MCQ",
    topic: "Inverse Ratio",
    question: "Two runners cover the same distance. The faster runner takes 6 hours and their speeds are in the ratio 4:3. How long does the slower runner take?",
    options: ["7 hours", "8 hours", "9 hours", "10 hours"],
    answer: "B",
    correctAnswer: "8 hours",
    solution: "For same distance, time ratio is inverse of speed ratio. Speed ratio faster:slower = 4:3, so time ratio = 3:4. Faster time = 6 hours = 3 parts, so 1 part = 2 hours. Slower time = 4 parts = 8 hours.",
    shortcut: "Same distance: faster speed means smaller time."
  },
  {
    id: "AS-U3-C-32",
    unit: 3,
    category: "Concept MCQ",
    topic: "Average Speed",
    question: "A man covers a distance at 20 km/hr and returns at 30 km/hr. Find the average speed.",
    options: ["24 km/hr", "25 km/hr", "26 km/hr", "28 km/hr"],
    answer: "A",
    correctAnswer: "24 km/hr",
    solution: "Average speed for equal distance = 2×20×30/(20+30) = 1200/50 = 24 km/hr.",
    shortcut: "Equal distance average speed = 2ab/(a+b)."
  },
  {
    id: "AS-U3-C-33",
    unit: 3,
    category: "Concept MCQ",
    topic: "Distance Ratio",
    question: "Two bikes start from A and B towards each other at 16 km/hr and 21 km/hr. When they meet, the second bike has travelled 60 km more. Find the distance between A and B.",
    options: ["420 km", "432 km", "444 km", "456 km"],
    answer: "C",
    correctAnswer: "444 km",
    solution: "Since time is same, distance ratio = speed ratio = 16:21. Difference = 5 parts = 60 km. So 1 part = 12 km. Total distance = 37 parts = 37×12 = 444 km.",
    shortcut: "Same time: distance ratio = speed ratio."
  },
  {
    id: "AS-U3-C-34",
    unit: 3,
    category: "Concept MCQ",
    topic: "Same Time Different Speed",
    question: "If a person travels at 12 km/hr instead of 8 km/hr, he covers 20 km more in the same time. Find the actual distance at 8 km/hr.",
    options: ["30 km", "40 km", "50 km", "60 km"],
    answer: "B",
    correctAnswer: "40 km",
    solution: "Let time be t. Extra distance = (12-8)t = 20. So 4t = 20, t = 5 hours. Actual distance = 8×5 = 40 km.",
    shortcut: "Extra distance = speed difference × time."
  },
  {
    id: "AS-U3-C-35",
    unit: 3,
    category: "Concept MCQ",
    topic: "Fractional Journey",
    question: "A person covers 1/4 of a journey at 20 km/hr and the remaining at 60 km/hr. If total time is 10 hours, find the total distance.",
    options: ["300 km", "350 km", "400 km", "450 km"],
    answer: "C",
    correctAnswer: "400 km",
    solution: "Let total distance be D. Time = (D/4)/20 + (3D/4)/60 = D/80 + D/80 = D/40. Given D/40 = 10, so D = 400 km.",
    shortcut: "Convert each part of journey into time, then add."
  },

  // =====================
  // 10 TRICKY EXAM MCQs
  // =====================
  {
    id: "AS-U3-T-36",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Delayed Train Meeting",
    question: "Two stations B and M are 465 km apart. A train starts from B at 10 AM at 65 km/hr. Another train starts from M at 11 AM at 35 km/hr. When will they meet?",
    options: ["2 PM", "3 PM", "4 PM", "5 PM"],
    answer: "B",
    correctAnswer: "3 PM",
    solution: "First train travels for 1 hour before second starts, covering 65 km. Remaining distance = 465 - 65 = 400 km. Relative speed = 65 + 35 = 100 km/hr. Time after 11 AM = 400/100 = 4 hours. Meeting time = 3 PM.",
    shortcut: "Distance left after early start ÷ relative speed."
  },
  {
    id: "AS-U3-T-37",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Same Direction Trains",
    question: "A train travelling at 25 km/hr leaves Delhi at 9 AM. Another train travelling at 35 km/hr leaves Delhi at 2 PM in the same direction. How far from Delhi will the second train catch the first?",
    options: ["350 km", "400 km", "437.5 km", "450 km"],
    answer: "C",
    correctAnswer: "437.5 km",
    solution: "First train has 5 hours lead, so distance lead = 25×5 = 125 km. Relative speed = 35 - 25 = 10 km/hr. Catch time after 2 PM = 125/10 = 12.5 hours. Distance from Delhi = 35×12.5 = 437.5 km.",
    shortcut: "Catch time = lead distance / relative speed."
  },
  {
    id: "AS-U3-T-38",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Police Chase",
    question: "A police officer chases a thief. Their speeds are 8 km/hr and 6 km/hr respectively. If the police officer starts 10 minutes late, at what distance will he catch the thief?",
    options: ["2 km", "3 km", "4 km", "5 km"],
    answer: "C",
    correctAnswer: "4 km",
    solution: "Thief's lead in 10 minutes = 6×10/60 = 1 km. Relative speed = 8 - 6 = 2 km/hr. Time to catch = 1/2 hour. Distance covered by police = 8×1/2 = 4 km.",
    shortcut: "Catch distance = chaser speed × catch time."
  },
  {
    id: "AS-U3-T-39",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Speed Reduction",
    question: "An aircraft covers 600 km. Due to bad weather, its speed is reduced by 200 km/hr and the flight takes 30 minutes more. Find the original speed.",
    options: ["400 km/hr", "500 km/hr", "600 km/hr", "800 km/hr"],
    answer: "C",
    correctAnswer: "600 km/hr",
    solution: "Let original speed be x. Then 600/(x-200) - 600/x = 1/2. Solving gives x = 600 km/hr.",
    shortcut: "Use increased time = new time - old time."
  },
  {
    id: "AS-U3-T-40",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Late Train",
    question: "If a train runs at 40 km/hr, it reaches 11 minutes late. If it runs at 50 km/hr, it reaches 5 minutes late. Find the correct time for the journey.",
    options: ["18 minutes", "19 minutes", "20 minutes", "21 minutes"],
    answer: "B",
    correctAnswer: "19 minutes",
    solution: "Speed ratio = 40:50 = 4:5. Time ratio = 5:4. Difference in time = 11 - 5 = 6 minutes = 1 part. Time at 40 km/hr = 5 parts = 30 minutes. Correct time = 30 - 11 = 19 minutes.",
    shortcut: "Use speed ratio to get inverse time ratio."
  },
  {
    id: "AS-U3-T-41",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Accident Speed Reduction",
    question: "A train runs at 3/5 of its former speed after an accident. If the accident had happened 30 km further, the delay would reduce by 24 minutes. Find the original speed.",
    options: ["40 km/hr", "50 km/hr", "60 km/hr", "75 km/hr"],
    answer: "B",
    correctAnswer: "50 km/hr",
    solution: "Let original speed be S. Reduced speed = 3S/5. Extra delay for 30 km = 30/(3S/5) - 30/S = 20/S. Given 24 minutes = 0.4 hour. So 20/S = 0.4, S = 50 km/hr.",
    shortcut: "Delay saved comes from 30 km being covered at original speed instead of reduced speed."
  },
  {
    id: "AS-U3-T-42",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Stoppage",
    question: "A train travels 600 km at 100 km/hr and stops for 3 minutes after every 75 km. Find the total time taken.",
    options: ["6 hours 21 minutes", "6 hours 24 minutes", "6 hours 27 minutes", "6 hours 30 minutes"],
    answer: "A",
    correctAnswer: "6 hours 21 minutes",
    solution: "Running time = 600/100 = 6 hours. Stops before destination = 600/75 - 1 = 8 - 1 = 7 stops. Total stoppage = 7×3 = 21 minutes. Total = 6 hours 21 minutes.",
    shortcut: "Number of stops = total sections - 1."
  },
  {
    id: "AS-U3-T-43",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Two Modes",
    question: "A man travels 61 km in 9 hours, partly on foot at 4 km/hr and partly by bicycle at 9 km/hr. How far did he travel on foot?",
    options: ["12 km", "14 km", "16 km", "18 km"],
    answer: "C",
    correctAnswer: "16 km",
    solution: "Let foot distance be x. Then x/4 + (61-x)/9 = 9. Multiplying by 36 gives 9x + 244 - 4x = 324. So 5x = 80 and x = 16 km.",
    shortcut: "Let slower-mode distance be x and form total time equation."
  },
  {
    id: "AS-U3-T-44",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Two Trains",
    question: "A train leaves Station A at 4 AM and reaches Station B at 10 AM. Another train leaves Station B at 6 AM and reaches Station A at 12 PM. At what time will they meet?",
    options: ["7:30 AM", "8:00 AM", "8:30 AM", "9:00 AM"],
    answer: "B",
    correctAnswer: "8:00 AM",
    solution: "Both trains take 6 hours to cover the full distance, so their speeds are equal. By 6 AM, the first train has already travelled 2/6 = 1/3 of the distance. Remaining distance = 2/3. Together, they cover 2/6 = 1/3 of the distance per hour. Time to meet after 6 AM = (2/3)/(1/3) = 2 hours. Meeting time = 8 AM.",
    shortcut: "If both trains take same total time, their speeds are equal."
  },
  {
    id: "AS-U3-T-45",
    unit: 3,
    category: "Tricky Exam MCQ",
    topic: "Stoppage",
    question: "Without stoppage, a bus travels at 60 km/hr. Including stoppages, it travels at 40 km/hr. How many minutes does it stop per hour?",
    options: ["10 minutes", "15 minutes", "20 minutes", "25 minutes"],
    answer: "C",
    correctAnswer: "20 minutes",
    solution: "In 1 hour including stoppage, distance = 40 km. Time required to cover 40 km at 60 km/hr = 40/60 hour = 2/3 hour = 40 minutes. Stop time = 60 - 40 = 20 minutes.",
    shortcut: "Stop time per hour = 60 × (1 - actual speed/running speed)."
  }
];

window.analyticalUnit3MCQs = analyticalUnit3MCQs;
