// analytical_unit1_mcq.js
// Unit 1: Time and Work
// 15 Self-Assessment Based + 20 Concept MCQs + 10 Tricky Exam MCQs

const analyticalUnit1MCQs = [
  // =========================
  // 15 SELF-ASSESSMENT BASED
  // =========================
  {
    id: "AS-U1-SA-01",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Time and Work",
    question: "If A and B together can complete a work in 15 days and B alone can complete it in 20 days, then A alone can complete the work in:",
    options: ["60 days", "45 days", "40 days", "30 days"],
    answer: "A",
    correctAnswer: "60 days",
    solution: "A's 1-day work = 1/15 - 1/20 = (4 - 3)/60 = 1/60. So, A alone takes 60 days.",
    shortcut: "Unknown work rate = Combined rate - Known person's rate."
  },
  {
    id: "AS-U1-SA-02",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Pair Work",
    question: "P and Q can finish a work in 12 days, Q and R in 15 days, and R and P in 20 days. In how many days can P alone finish it?",
    options: ["10 days", "20 days", "30 days", "60 days"],
    answer: "C",
    correctAnswer: "30 days",
    solution: "P+Q = 1/12, Q+R = 1/15, R+P = 1/20. Adding: 2(P+Q+R) = 1/12 + 1/15 + 1/20 = 1/5. So P+Q+R = 1/10. P = 1/10 - 1/15 = 1/30.",
    shortcut: "For pair work: Add all pairs, divide by 2, then subtract the pair not containing the required person."
  },
  {
    id: "AS-U1-SA-03",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Men-Women Work",
    question: "20 women can lay a 100 m road in 10 days. How many days will 10 women take to lay a 50 m road?",
    options: ["20 days", "15 days", "5 days", "10 days"],
    answer: "D",
    correctAnswer: "10 days",
    solution: "Work is proportional to length. Required days = (20 × 10 × 50) / (10 × 100) = 10 days.",
    shortcut: "Use M1D1/W1 = M2D2/W2."
  },
  {
    id: "AS-U1-SA-04",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Three Workers",
    question: "A and B can finish a work in 36 days, B and C in 24 days, and A and C in 18 days. In how many days can A, B and C together finish it?",
    options: ["8 days", "16 days", "30 days", "32 days"],
    answer: "B",
    correctAnswer: "16 days",
    solution: "AB + BC + AC = 1/36 + 1/24 + 1/18 = 1/8. This equals 2(A+B+C). So A+B+C = 1/16. Hence, they finish in 16 days.",
    shortcut: "For three pair-combinations: Total rate = Sum of pair rates ÷ 2."
  },
  {
    id: "AS-U1-SA-05",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Individual Work",
    question: "Ganesh, Ram and Sohan together can complete a work in 16 days. Ganesh and Ram together can complete it in 24 days. How many days will Sohan alone take?",
    options: ["40 days", "48 days", "32 days", "30 days"],
    answer: "B",
    correctAnswer: "48 days",
    solution: "Sohan's rate = 1/16 - 1/24 = (3 - 2)/48 = 1/48. So Sohan alone takes 48 days.",
    shortcut: "Single worker rate = Total group rate - Other group rate."
  },
  {
    id: "AS-U1-SA-06",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Leaving Work",
    question: "A and B can complete a work in 15 days and 10 days respectively. They work together for 2 days, then B leaves. In how many total days is the work completed?",
    options: ["10 days", "8 days", "12 days", "15 days"],
    answer: "C",
    correctAnswer: "12 days",
    solution: "LCM of 15 and 10 = 30 units. A = 2 units/day, B = 3 units/day. Together in 2 days = 5 × 2 = 10 units. Remaining = 20 units. A alone completes 20 units in 20/2 = 10 days. Total = 2 + 10 = 12 days.",
    shortcut: "Use LCM method: Total work - work already done = remaining work."
  },
  {
    id: "AS-U1-SA-07",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Man and Boy",
    question: "A man and a boy together can finish a work in 24 days. If the last 6 days are done by the man alone and the whole work finishes in 26 days, how many days will the boy alone take?",
    options: ["72 days", "20 days", "24 days", "36 days"],
    answer: "A",
    correctAnswer: "72 days",
    solution: "For first 20 days both work, then man alone works 6 days. Work done by both in 20 days = 20/24 = 5/6. Remaining = 1/6. Man does 1/6 in 6 days, so man alone takes 36 days. Boy's rate = 1/24 - 1/36 = 1/72.",
    shortcut: "Break the work into combined-days and alone-days."
  },
  {
    id: "AS-U1-SA-08",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Half-Day Work",
    question: "A and B together can complete a work in 12 days. A alone can complete it in 20 days. If B works only half a day daily, then A and B together will complete the work in:",
    options: ["10 days", "20 days", "11 days", "15 days"],
    answer: "D",
    correctAnswer: "15 days",
    solution: "B's full-day rate = 1/12 - 1/20 = 1/30. B's half-day rate = 1/60. New daily rate = 1/20 + 1/60 = 4/60 = 1/15. So time = 15 days.",
    shortcut: "Half-day work means half of the worker's full-day efficiency."
  },
  {
    id: "AS-U1-SA-09",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Remaining Work",
    question: "Ramesh and Rahman can do a work in 20 and 25 days respectively. They work together for 10 days and then leave. Suresh completes the remaining work in 3 days. How many days will Suresh alone take for the whole work?",
    options: ["32 days", "28 days", "29 days", "30 days"],
    answer: "D",
    correctAnswer: "30 days",
    solution: "Ramesh + Rahman rate = 1/20 + 1/25 = 9/100. Work done in 10 days = 90/100 = 9/10. Remaining = 1/10. Suresh does 1/10 in 3 days, so full work = 30 days.",
    shortcut: "If x fraction is done in n days, full work time = n/x."
  },
  {
    id: "AS-U1-SA-10",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Men Women Boys",
    question: "A man, a woman and a boy can complete a work in 20, 30 and 60 days respectively. How many boys must assist 2 men and 8 women to complete the work in 2 days?",
    options: ["8", "12", "4", "6"],
    answer: "A",
    correctAnswer: "8",
    solution: "Daily rate of 2 men = 2/20 = 1/10. Daily rate of 8 women = 8/30 = 4/15. Let boys = x, rate = x/60. In 2 days: 2(1/10 + 4/15 + x/60) = 1. Solving gives x = 8.",
    shortcut: "Convert each worker type into daily work rate, then multiply by days."
  },
  {
    id: "AS-U1-SA-11",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Men and Boys",
    question: "3 men and 4 boys can complete a work in 12 days. 4 men and 3 boys can complete the same work in 10 days. In how many days can 2 men and 3 boys finish it?",
    options: ["17.5 days", "5 5/11 days", "8 days", "22 days"],
    answer: "A",
    correctAnswer: "17.5 days",
    solution: "Let one man's rate be M and one boy's rate be B. 3M+4B = 1/12 and 4M+3B = 1/10. Solving gives M = 3/140 and B = 1/210. So 2M+3B = 2/35. Time = 35/2 = 17.5 days.",
    shortcut: "Make two equations using total daily work, then find required group rate."
  },
  {
    id: "AS-U1-SA-12",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Efficiency Ratio",
    question: "20 women can complete a work in 16 days. 16 men can complete the same work in 15 days. What is the efficiency ratio of a man to a woman?",
    options: ["3 : 4", "4 : 3", "5 : 3", "5 : 7"],
    answer: "B",
    correctAnswer: "4 : 3",
    solution: "20 women × 16 days = 320 woman-days. 16 men × 15 days = 240 man-days. Efficiency ratio man : woman = 320 : 240 = 4 : 3.",
    shortcut: "Efficiency is inverse of total worker-days."
  },
  {
    id: "AS-U1-SA-13",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Additional Workers",
    question: "A company employed 200 workers to complete a work in 150 days. After 50 days, only one-fourth of the work is done. How many additional workers are required to finish on time?",
    options: ["100", "300", "600", "200"],
    answer: "A",
    correctAnswer: "100",
    solution: "200 workers × 50 days = 1/4 work. Full work = 200 × 50 × 4 = 40000 worker-days. Remaining work = 30000 worker-days. Time left = 100 days. Required workers = 30000/100 = 300. Additional workers = 300 - 200 = 100.",
    shortcut: "Remaining workers needed = Remaining worker-days ÷ remaining days."
  },
  {
    id: "AS-U1-SA-14",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Efficiency Difference",
    question: "A is thrice as good a worker as B and finishes a job 40 days earlier than B. Working together, they can finish the job in:",
    options: ["14 days", "13 days", "20 days", "15 days"],
    answer: "D",
    correctAnswer: "15 days",
    solution: "Efficiency A:B = 3:1, so time A:B = 1:3. Let A = x days and B = 3x days. Difference = 2x = 40, so x = 20. A = 20 days, B = 60 days. Together rate = 1/20 + 1/60 = 1/15.",
    shortcut: "Efficiency ratio inverse gives time ratio."
  },
  {
    id: "AS-U1-SA-15",
    unit: 1,
    category: "Self-Assessment Based",
    topic: "Production Work",
    question: "4 mat-weavers can weave 4 mats in 4 days. At the same rate, how many mats can 8 mat-weavers weave in 8 days?",
    options: ["4", "8", "12", "16"],
    answer: "D",
    correctAnswer: "16",
    solution: "4 weavers × 4 days = 16 weaver-days make 4 mats. So 1 mat needs 4 weaver-days. 8 weavers × 8 days = 64 weaver-days. Mats = 64/4 = 16.",
    shortcut: "Production ∝ workers × days."
  },

  // =================
  // 20 CONCEPT MCQs
  // =================
  {
    id: "AS-U1-C-16",
    unit: 1,
    category: "Concept MCQ",
    topic: "Combined Work",
    question: "A can complete a work in 12 days and B in 18 days. In how many days can they complete it together?",
    options: ["7.2 days", "6 days", "8 days", "9 days"],
    answer: "A",
    correctAnswer: "7.2 days",
    solution: "LCM of 12 and 18 = 36. A's efficiency = 3 units/day, B's efficiency = 2 units/day. Together = 5 units/day. Time = 36/5 = 7.2 days.",
    shortcut: "Together time = Product of days ÷ Sum of days = 12×18/(12+18)."
  },
  {
    id: "AS-U1-C-17",
    unit: 1,
    category: "Concept MCQ",
    topic: "Percentage Efficiency",
    question: "A is 25% more efficient than B. If B can finish a work in 20 days, then A and B together can finish it in:",
    options: ["9 days", "80/9 days", "8 days", "10 days"],
    answer: "B",
    correctAnswer: "80/9 days",
    solution: "B's efficiency = 100, A's efficiency = 125. A's time = 20 × 100/125 = 16 days. Together rate = 1/16 + 1/20 = 9/80. Time = 80/9 days.",
    shortcut: "More efficient means less time: New time = Old time × old efficiency/new efficiency."
  },
  {
    id: "AS-U1-C-18",
    unit: 1,
    category: "Concept MCQ",
    topic: "Three Workers",
    question: "A, B and C can complete a work in 12, 15 and 20 days respectively. How many days will they take together?",
    options: ["6 days", "4 days", "5 days", "7 days"],
    answer: "C",
    correctAnswer: "5 days",
    solution: "LCM = 60. A = 5 units/day, B = 4 units/day, C = 3 units/day. Together = 12 units/day. Time = 60/12 = 5 days.",
    shortcut: "Take LCM as total work and add daily efficiencies."
  },
  {
    id: "AS-U1-C-19",
    unit: 1,
    category: "Concept MCQ",
    topic: "Find Individual Time",
    question: "A and B together can finish a work in 10 days. A alone can finish it in 15 days. How many days will B alone take?",
    options: ["20 days", "25 days", "15 days", "30 days"],
    answer: "D",
    correctAnswer: "30 days",
    solution: "B's rate = 1/10 - 1/15 = 1/30. Hence, B alone takes 30 days.",
    shortcut: "B alone = 1 / (Combined rate - A's rate)."
  },
  {
    id: "AS-U1-C-20",
    unit: 1,
    category: "Concept MCQ",
    topic: "Leaving Work",
    question: "A can finish a work in 10 days and B in 15 days. They work together for 3 days, then A leaves. How many more days will B take to finish the remaining work?",
    options: ["6 days", "7.5 days", "9 days", "10 days"],
    answer: "B",
    correctAnswer: "7.5 days",
    solution: "LCM = 30. A = 3 units/day, B = 2 units/day. Together in 3 days = 15 units. Remaining = 15 units. B takes 15/2 = 7.5 days.",
    shortcut: "Remaining days = Remaining work ÷ remaining worker's efficiency."
  },
  {
    id: "AS-U1-C-21",
    unit: 1,
    category: "Concept MCQ",
    topic: "Alternate Days",
    question: "A can complete a work in 12 days and B in 18 days. If they work on alternate days starting with A, then total time required is:",
    options: ["15 days", "12 days", "14 days", "14 1/3 days"],
    answer: "D",
    correctAnswer: "14 1/3 days",
    solution: "LCM = 36. A = 3 units/day, B = 2 units/day. In 2 days they do 5 units. In 14 days they do 35 units. Remaining = 1 unit. A does 3 units/day, so 1 unit takes 1/3 day. Total = 14 1/3 days.",
    shortcut: "For alternate days, calculate work done in a 2-day cycle."
  },
  {
    id: "AS-U1-C-22",
    unit: 1,
    category: "Concept MCQ",
    topic: "Pattern Work",
    question: "A can finish a work in 10 days and B in 15 days. A works on the first two days and B works on the third day. This pattern repeats. In how many days is the work completed?",
    options: ["9 days", "10 days", "11 days", "12 days"],
    answer: "C",
    correctAnswer: "11 days",
    solution: "LCM = 30. A = 3 units/day, B = 2 units/day. In 3 days: A + A + B = 3 + 3 + 2 = 8 units. In 9 days = 24 units. Day 10 A does 3 units, total 27. Day 11 A does remaining 3 units. Work completes on day 11.",
    shortcut: "Find work per repeating cycle, then handle remaining work day-wise."
  },
  {
    id: "AS-U1-C-23",
    unit: 1,
    category: "Concept MCQ",
    topic: "Workers and Days",
    question: "5 men can complete a work in 12 days. How many days will 8 men take to complete the same work?",
    options: ["7.5 days", "8 days", "9.5 days", "10 days"],
    answer: "A",
    correctAnswer: "7.5 days",
    solution: "Total work = 5 × 12 = 60 man-days. Time for 8 men = 60/8 = 7.5 days.",
    shortcut: "For same work: M1D1 = M2D2."
  },
  {
    id: "AS-U1-C-24",
    unit: 1,
    category: "Concept MCQ",
    topic: "Hours and Work",
    question: "6 workers working 8 hours daily complete a work in 10 days. How many days will 8 workers working 6 hours daily take?",
    options: ["8 days", "9 days", "10 days", "12 days"],
    answer: "C",
    correctAnswer: "10 days",
    solution: "Using M1D1H1 = M2D2H2: 6×10×8 = 8×D×6. So D = 10 days.",
    shortcut: "Use MDH formula when hours are included."
  },
  {
    id: "AS-U1-C-25",
    unit: 1,
    category: "Concept MCQ",
    topic: "Partial Work",
    question: "12 men can complete a work in 15 days. They work for 5 days, then only 8 men continue. In how many total days will the work be completed?",
    options: ["15 days", "18 days", "19 days", "20 days"],
    answer: "D",
    correctAnswer: "20 days",
    solution: "Total work = 12×15 = 180 man-days. Work done in 5 days = 12×5 = 60. Remaining = 120. 8 men need 120/8 = 15 more days. Total = 5+15 = 20 days.",
    shortcut: "Total man-days - completed man-days = remaining man-days."
  },
  {
    id: "AS-U1-C-26",
    unit: 1,
    category: "Concept MCQ",
    topic: "Fractional Work",
    question: "A completes 1/3 of a work in 6 days. How many days will A take to complete the full work?",
    options: ["12 days", "18 days", "20 days", "24 days"],
    answer: "B",
    correctAnswer: "18 days",
    solution: "If 1/3 work takes 6 days, full work takes 6×3 = 18 days.",
    shortcut: "Full time = Time taken ÷ fraction completed."
  },
  {
    id: "AS-U1-C-27",
    unit: 1,
    category: "Concept MCQ",
    topic: "Fractional Combined Work",
    question: "A completes 2/5 of a work in 8 days. B completes 1/3 of the same work in 6 days. Together, they can complete the whole work in:",
    options: ["180/19 days", "19/180 days", "10 days", "12 days"],
    answer: "A",
    correctAnswer: "180/19 days",
    solution: "A's full time = 8 ÷ 2/5 = 20 days. B's full time = 6 ÷ 1/3 = 18 days. Together rate = 1/20 + 1/18 = 19/180. Time = 180/19 days.",
    shortcut: "First convert fractional work to full-work time, then add rates."
  },
  {
    id: "AS-U1-C-28",
    unit: 1,
    category: "Concept MCQ",
    topic: "Efficiency Ratio",
    question: "A works twice as fast as B. If A and B together complete a work in 12 days, then B alone will complete it in:",
    options: ["18 days", "24 days", "36 days", "48 days"],
    answer: "C",
    correctAnswer: "36 days",
    solution: "Efficiency A:B = 2:1. Together efficiency = 3 parts. If together takes 12 days, total work = 3×12 = 36 parts. B alone does 1 part/day, so B takes 36 days.",
    shortcut: "Total work = Combined efficiency × combined days."
  },
  {
    id: "AS-U1-C-29",
    unit: 1,
    category: "Concept MCQ",
    topic: "Efficiency Percentage",
    question: "A is 40% more efficient than B. If A completes a work in 30 days, then B will complete the same work in:",
    options: ["36 days", "38 days", "40 days", "42 days"],
    answer: "D",
    correctAnswer: "42 days",
    solution: "A's efficiency is 140% of B. Time is inverse of efficiency. B's time = 30 × 140/100 = 42 days.",
    shortcut: "If A is 40% more efficient, B takes 1.4 times A's time."
  },
  {
    id: "AS-U1-C-30",
    unit: 1,
    category: "Concept MCQ",
    topic: "Men and Women Conversion",
    question: "If 2 men can do the same work as 3 women, and 4 men can finish a job in 15 days, then 3 men and 3 women will finish it in:",
    options: ["12 days", "10 days", "15 days", "18 days"],
    answer: "A",
    correctAnswer: "12 days",
    solution: "2 men = 3 women, so 3 women = 2 men. Therefore, 3 men + 3 women = 3 men + 2 men = 5 men. Total work = 4×15 = 60 man-days. Time = 60/5 = 12 days.",
    shortcut: "Convert all workers into one common type."
  },
  {
    id: "AS-U1-C-31",
    unit: 1,
    category: "Concept MCQ",
    topic: "Wages",
    question: "A can complete a work in 10 days and B in 15 days. They work together and receive ₹2500. What is B's share?",
    options: ["₹1500", "₹1000", "₹1200", "₹900"],
    answer: "B",
    correctAnswer: "₹1000",
    solution: "Efficiency ratio A:B = 1/10 : 1/15 = 3:2. Total wage = ₹2500. B's share = 2/5 × 2500 = ₹1000.",
    shortcut: "If workers work for same days, divide wages in efficiency ratio."
  },
  {
    id: "AS-U1-C-32",
    unit: 1,
    category: "Concept MCQ",
    topic: "Wages with Leaving",
    question: "A can finish a work in 12 days and B in 20 days. A works for 4 days, then B completes the remaining work. If total wage is ₹1200, B's share is:",
    options: ["₹600", "₹700", "₹800", "₹900"],
    answer: "C",
    correctAnswer: "₹800",
    solution: "LCM = 60. A = 5 units/day, B = 3 units/day. A works 4 days = 20 units. Remaining = 40 units done by B. Work ratio A:B = 20:40 = 1:2. B's share = 2/3 × 1200 = ₹800.",
    shortcut: "When days are different, divide wages according to actual work done."
  },
  {
    id: "AS-U1-C-33",
    unit: 1,
    category: "Concept MCQ",
    topic: "Wages Among Three",
    question: "A, B and C can complete a work in 12, 18 and 24 days respectively. They work for 3, 4 and 6 days respectively. If total wage is ₹2600, what is C's share?",
    options: ["₹700", "₹800", "₹850", "₹900"],
    answer: "D",
    correctAnswer: "₹900",
    solution: "LCM = 72. A = 6, B = 4, C = 3 units/day. Work done: A = 18, B = 16, C = 18. Ratio = 18:16:18 = 9:8:9. Total parts = 26. C's share = 9/26 × 2600 = ₹900.",
    shortcut: "Work done = efficiency × number of days."
  },
  {
    id: "AS-U1-C-34",
    unit: 1,
    category: "Concept MCQ",
    topic: "Production",
    question: "10 men working 8 hours daily for 12 days make 240 toys. How many toys will 8 men make by working 6 hours daily for 10 days?",
    options: ["120 toys", "140 toys", "160 toys", "180 toys"],
    answer: "A",
    correctAnswer: "120 toys",
    solution: "Toys ∝ men × days × hours. Required toys = 240 × (8×10×6)/(10×12×8) = 120 toys.",
    shortcut: "Work output ratio = M2D2H2 / M1D1H1."
  },
  {
    id: "AS-U1-C-35",
    unit: 1,
    category: "Concept MCQ",
    topic: "Efficiency in MDH",
    question: "12 workers with 100% efficiency complete a work in 20 days. How many days will 10 workers with 150% efficiency take?",
    options: ["14 days", "16 days", "18 days", "20 days"],
    answer: "B",
    correctAnswer: "16 days",
    solution: "Use MDE formula: 12×20×100 = 10×D×150. So D = 24000/1500 = 16 days.",
    shortcut: "For same work: M1D1E1 = M2D2E2."
  },

  // =====================
  // 10 TRICKY EXAM MCQs
  // =====================
  {
    id: "AS-U1-T-36",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Pair Work",
    question: "A and B can do a work in 18 days, B and C in 24 days, and C and A in 36 days. In how many days can A, B and C together complete it?",
    options: ["12 days", "14 days", "16 days", "18 days"],
    answer: "C",
    correctAnswer: "16 days",
    solution: "AB + BC + CA = 1/18 + 1/24 + 1/36 = 1/8. This is equal to 2(A+B+C). So A+B+C = 1/16. Hence, time = 16 days.",
    shortcut: "In pair-work questions, combined rate of all three = sum of pair rates ÷ 2."
  },
  {
    id: "AS-U1-T-37",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Time Difference",
    question: "A takes 10 days less than B to finish a work. If A and B together can finish the work in 12 days, then B alone will take:",
    options: ["30 days", "25 days", "20 days", "27 days"],
    answer: "A",
    correctAnswer: "30 days",
    solution: "Let A = x days and B = x+10 days. Then 1/x + 1/(x+10) = 1/12. Solving: x = 20. So B = 30 days.",
    shortcut: "For difference-based questions, assume slower worker time = faster worker time + difference."
  },
  {
    id: "AS-U1-T-38",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Efficiency Chain",
    question: "A is twice as efficient as B, and B is twice as efficient as C. If A and B together finish a work in 4 days, then C alone will finish it in:",
    options: ["12 days", "18 days", "24 days", "30 days"],
    answer: "C",
    correctAnswer: "24 days",
    solution: "Efficiency C:B:A = 1:2:4. A+B = 6 units/day. In 4 days, total work = 24 units. C does 1 unit/day, so C alone takes 24 days.",
    shortcut: "Build efficiency chain first, then total work = combined efficiency × days."
  },
  {
    id: "AS-U1-T-39",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Percentage Efficiency",
    question: "A can complete a work in 70 days. B is 40% more efficient than A. How many days will B take?",
    options: ["40 days", "50 days", "60 days", "45 days"],
    answer: "B",
    correctAnswer: "50 days",
    solution: "B's efficiency = 140% of A. Time taken by B = 70 × 100/140 = 50 days.",
    shortcut: "More efficiency means less time: New time = Old time × 100/(100 + percentage increase)."
  },
  {
    id: "AS-U1-T-40",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Work Ratio",
    question: "5 men and 2 women can do four times as much work per hour as 1 man and 1 woman together. What is the efficiency ratio of a man to a woman?",
    options: ["2 : 1", "1 : 2", "3 : 1", "1 : 3"],
    answer: "A",
    correctAnswer: "2 : 1",
    solution: "Let man = M and woman = W. Given 5M + 2W = 4(M + W). So 5M + 2W = 4M + 4W, hence M = 2W. Ratio M:W = 2:1.",
    shortcut: "Convert the statement into an equation using M and W."
  },
  {
    id: "AS-U1-T-41",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Men Days Hours",
    question: "15 men take 20 days to complete a job working 8 hours a day. How many hours per day should 20 men work to complete the job in 12 days?",
    options: ["5 hours", "8 hours", "10 hours", "15 hours"],
    answer: "C",
    correctAnswer: "10 hours",
    solution: "Using M1D1H1 = M2D2H2: 15×20×8 = 20×12×H. H = 10 hours.",
    shortcut: "Use MDH formula whenever men, days and hours are given."
  },
  {
    id: "AS-U1-T-42",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Men and Women Equations",
    question: "4 men and 6 women can complete a work in 8 days, while 3 men and 7 women can complete it in 10 days. In how many days can 10 women complete it?",
    options: ["35 days", "45 days", "40 days", "50 days"],
    answer: "C",
    correctAnswer: "40 days",
    solution: "4M+6W = 1/8 and 3M+7W = 1/10. Solving gives W = 1/400. So 10 women work rate = 10/400 = 1/40. Hence, 10 women take 40 days.",
    shortcut: "Create two equations and eliminate M to find W."
  },
  {
    id: "AS-U1-T-43",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Hourly Work",
    question: "Working 7 hours a day, A alone completes a work in 6 days and B alone in 8 days. If they work together for 8 hours a day, then they finish the work in:",
    options: ["3 days", "4 days", "2.5 days", "3.6 days"],
    answer: "A",
    correctAnswer: "3 days",
    solution: "A needs 6×7 = 42 hours. B needs 8×7 = 56 hours. Together hourly rate = 1/42 + 1/56 = 1/24. They need 24 hours together. At 8 hours/day, days = 24/8 = 3 days.",
    shortcut: "Convert days into total hours first."
  },
  {
    id: "AS-U1-T-44",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Daily Wage",
    question: "A daily-wage labourer was engaged for certain days for ₹5750, but due to absence he was paid only ₹5000. What is the maximum possible daily wage?",
    options: ["₹125", "₹250", "₹375", "₹500"],
    answer: "B",
    correctAnswer: "₹250",
    solution: "Daily wage must divide both ₹5750 and ₹5000 exactly. Maximum possible daily wage = HCF/GCD of 5750 and 5000 = ₹250.",
    shortcut: "Maximum possible daily wage = HCF of total promised wage and actual paid wage."
  },
  {
    id: "AS-U1-T-45",
    unit: 1,
    category: "Tricky Exam MCQ",
    topic: "Efficiency Comparison",
    question: "A does half as much work as B in three-fourths of the time. If together they complete a work in 18 days, then how many days will B alone take?",
    options: ["30 days", "35 days", "40 days", "45 days"],
    answer: "A",
    correctAnswer: "30 days",
    solution: "A's work compared to B = 1/2, and A's time compared to B = 3/4. So efficiency A:B = (1/2)/(3/4) = 2:3. Together efficiency = 5 parts. Total work = 5×18 = 90 parts. B does 3 parts/day, so B alone takes 90/3 = 30 days.",
    shortcut: "Efficiency ratio = Work ratio ÷ Time ratio."
  }
];

window.analyticalUnit1MCQs = analyticalUnit1MCQs;
