// unit2_mcq.js
// Analytical Skills-II
// Unit 2: Pipes and Cistern
// 15 Self-Assessment Based + 20 Concept MCQs + 10 Tricky Exam MCQs

const analyticalUnit2MCQs = [
  // =========================
  // 15 SELF-ASSESSMENT BASED
  // =========================
  {
    id: "AS-U2-SA-01",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Inlet and Outlet Pipes",
    question: "Pipe A fills a tank in 5 hours, Pipe B fills it in 6 hours, and Pipe C empties it in 12 hours. If all three are opened together, the tank will be filled in:",
    options: ["60/13 hours", "60/15 hours", "60/17 hours", "60/19 hours"],
    answer: "C",
    correctAnswer: "60/17 hours",
    solution: "Net rate = 1/5 + 1/6 - 1/12 = (12 + 10 - 5)/60 = 17/60 tank/hour. Time = 1 ÷ 17/60 = 60/17 hours.",
    shortcut: "Inlet is positive, outlet is negative: Net rate = fill rates - empty rate."
  },
  {
    id: "AS-U2-SA-02",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Multiple Inlet Pipes",
    question: "Pipe A fills a tank in 8 hours, Pipe B in 4 hours, and Pipe C in 24 hours. If all pipes are opened together, the tank will be filled in:",
    options: ["2.4 hours", "3 hours", "4 hours", "4.2 hours"],
    answer: "A",
    correctAnswer: "2.4 hours",
    solution: "Combined rate = 1/8 + 1/4 + 1/24 = 3/24 + 6/24 + 1/24 = 10/24 = 5/12. Time = 12/5 = 2.4 hours.",
    shortcut: "For all filling pipes, add their one-hour work."
  },
  {
    id: "AS-U2-SA-03",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Two Inlet Pipes",
    question: "Two pipes can fill a tank in 2 minutes and 6 minutes respectively. If both are opened together, the tank will be filled in:",
    options: ["3 minutes", "2.5 minutes", "2 minutes", "1.5 minutes"],
    answer: "D",
    correctAnswer: "1.5 minutes",
    solution: "Combined rate = 1/2 + 1/6 = 4/6 = 2/3 tank/min. Time = 1 ÷ 2/3 = 3/2 = 1.5 minutes.",
    shortcut: "Together time = xy / (x + y)."
  },
  {
    id: "AS-U2-SA-04",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Two Outlet Pipes",
    question: "Two outlet pipes empty a full tank in 10 minutes and 30 minutes respectively. If both are opened together, the tank will empty in:",
    options: ["7 minutes", "7 minutes 30 seconds", "6 minutes", "6 minutes 30 seconds"],
    answer: "B",
    correctAnswer: "7 minutes 30 seconds",
    solution: "Combined emptying rate = 1/10 + 1/30 = 4/30 = 2/15 tank/min. Time = 15/2 = 7.5 minutes = 7 minutes 30 seconds.",
    shortcut: "For two outlet pipes, add their emptying rates."
  },
  {
    id: "AS-U2-SA-05",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Three Inlets and One Outlet",
    question: "Pipes A, B and C fill a tank in 12, 15 and 20 minutes respectively. Pipe D empties it in 30 minutes. If all are opened together, the tank fills in:",
    options: ["5 minutes", "6 minutes", "7 minutes", "8 minutes"],
    answer: "B",
    correctAnswer: "6 minutes",
    solution: "LCM of 12, 15, 20 and 30 = 60. A = 5, B = 4, C = 3, D = -2 units/min. Net = 5 + 4 + 3 - 2 = 10 units/min. Time = 60/10 = 6 minutes.",
    shortcut: "Use LCM as tank capacity, then add positive and negative efficiencies."
  },
  {
    id: "AS-U2-SA-06",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Inlet and Leak",
    question: "Pipes A and B fill a tank in 8 and 24 hours respectively. Pipe C empties it in 12 hours. If all are opened together, the tank will be filled in:",
    options: ["18 hours", "6 hours", "24 hours", "12 hours"],
    answer: "D",
    correctAnswer: "12 hours",
    solution: "Net rate = 1/8 + 1/24 - 1/12 = 3/24 + 1/24 - 2/24 = 2/24 = 1/12. Time = 12 hours.",
    shortcut: "Net filling time = 1 / net filling rate."
  },
  {
    id: "AS-U2-SA-07",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Partially Filled Tank",
    question: "A tank is 2/5 full. Pipe A fills it in 10 minutes and Pipe B empties it in 6 minutes. If both are opened, the tank will:",
    options: ["Empty in 6 minutes", "Fill in 6 minutes", "Empty in 9 minutes", "Fill in 9 minutes"],
    answer: "A",
    correctAnswer: "Empty in 6 minutes",
    solution: "Net emptying rate = 1/6 - 1/10 = 4/60 = 1/15 tank/min. Water present = 2/5. Time to empty = (2/5) ÷ (1/15) = 6 minutes.",
    shortcut: "When emptying rate is greater, use current water level ÷ net emptying rate."
  },
  {
    id: "AS-U2-SA-08",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Mixture in Tank",
    question: "Three pipes A, B and C fill a tank in 30, 20 and 10 minutes respectively. They discharge solutions P, Q and R. What is the proportion of solution R in the tank?",
    options: ["5/11", "6/11", "8/11", "7/11"],
    answer: "B",
    correctAnswer: "6/11",
    solution: "Rates are A = 1/30, B = 1/20, C = 1/10. Ratio = 2 : 3 : 6. Total = 11 parts. Solution R comes from C, so proportion = 6/11.",
    shortcut: "Mixture ratio = individual filling rates ratio."
  },
  {
    id: "AS-U2-SA-09",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Capacity and Buckets",
    question: "13 buckets of 51 litres each fill a tank. How many buckets of 17 litres each are required to fill the same tank?",
    options: ["33", "29", "39", "42"],
    answer: "C",
    correctAnswer: "39",
    solution: "Tank capacity = 13 × 51 = 663 litres. Required buckets = 663/17 = 39.",
    shortcut: "Same capacity: Old buckets × old size = New buckets × new size."
  },
  {
    id: "AS-U2-SA-10",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Finding Leak Time",
    question: "Pipe A fills a tank in 40 minutes and Pipe B in 30 minutes. A leak is also present. If all three together fill the tank in 20 minutes, then the leak alone can empty it in:",
    options: ["120 minutes", "100 minutes", "140 minutes", "80 minutes"],
    answer: "A",
    correctAnswer: "120 minutes",
    solution: "A+B rate = 1/40 + 1/30 = 7/120. Net rate = 1/20 = 6/120. Leak rate = 7/120 - 6/120 = 1/120. So leak empties in 120 minutes.",
    shortcut: "Leak rate = Filling rate without leak - actual net filling rate."
  },
  {
    id: "AS-U2-SA-11",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Leakage",
    question: "Two taps fill a tank in 5 hours and 20 hours respectively. Due to leakage, they take 40 minutes extra. The leak alone can empty the full tank in:",
    options: ["28 hours", "16 hours", "22 hours", "32 hours"],
    answer: "A",
    correctAnswer: "28 hours",
    solution: "Without leak, rate = 1/5 + 1/20 = 1/4, so time = 4 hours. With leak, time = 4 hours 40 minutes = 14/3 hours. Net rate = 3/14. Leak rate = 1/4 - 3/14 = 1/28. So leak empties in 28 hours.",
    shortcut: "Convert extra minutes into hours before using rates."
  },
  {
    id: "AS-U2-SA-12",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Tank Capacity",
    question: "A leak can empty a full tank in 6 hours. An inlet pipe fills water at 4 litres/minute. When the tank is full and inlet is open, the tank becomes empty in 24 hours due to the leak. Find the tank capacity.",
    options: ["4010 litres", "2220 litres", "1920 litres", "2020 litres"],
    answer: "C",
    correctAnswer: "1920 litres",
    solution: "Let capacity = C litres. Leak rate = C/360 litres/min. Net emptying rate = C/1440 litres/min. So C/360 - 4 = C/1440. Solving gives C = 1920 litres.",
    shortcut: "Use litres/minute when a pipe rate is given in litres/minute."
  },
  {
    id: "AS-U2-SA-13",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Alternate Pipes",
    question: "Taps A, B and C fill a tank in 12, 15 and 20 hours respectively. A is always open, while B and C are opened alternately for one hour each. If B starts first, the tank will be full in:",
    options: ["20/3 hours", "6 hours", "15/2 hours", "7 hours"],
    answer: "D",
    correctAnswer: "7 hours",
    solution: "A+B rate = 1/12 + 1/15 = 3/20. A+C rate = 1/12 + 1/20 = 2/15. In 2 hours work = 3/20 + 2/15 = 17/60. In 6 hours = 51/60. Remaining = 9/60, completed in the next A+B hour. Total = 7 hours.",
    shortcut: "For alternate pipes, calculate work done in a 2-hour cycle."
  },
  {
    id: "AS-U2-SA-14",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "Half-Time Pipe Use",
    question: "Pipe A fills a tanker in 60 minutes and Pipe B in 40 minutes. B works alone for half the total time, and A+B work together for the other half. Total time required is:",
    options: ["15 minutes", "20 minutes", "27.5 minutes", "30 minutes"],
    answer: "A",
    correctAnswer: "15 minutes",
    solution: "Let total time be T. Work = T/2 × 1/40 + T/2 × (1/60 + 1/40). So work = T/80 + T/48 = T/30. For full tank, T/30 = 1, so T = 15 minutes.",
    shortcut: "When half-time is given, multiply each rate by T/2."
  },
  {
    id: "AS-U2-SA-15",
    unit: 2,
    category: "Self-Assessment Based",
    topic: "One Pipe Closed",
    question: "Three pipes A, B and C together fill a tank in 6 hours. After working together for 2 hours, C is closed and A+B fill the remaining part in 7 hours. C alone can fill the tank in:",
    options: ["10 hours", "12 hours", "14 hours", "16 hours"],
    answer: "C",
    correctAnswer: "14 hours",
    solution: "All three rate = 1/6. In 2 hours, work done = 2/6 = 1/3. Remaining = 2/3. A+B fill 2/3 in 7 hours, so A+B rate = 2/21. C rate = 1/6 - 2/21 = 1/14. Hence C alone takes 14 hours.",
    shortcut: "C rate = total rate - A+B rate."
  },

  // =================
  // 20 CONCEPT MCQs
  // =================
  {
    id: "AS-U2-C-16",
    unit: 2,
    category: "Concept MCQ",
    topic: "Two Pipes Together",
    question: "Two pipes fill a tank in 12 hours and 16 hours respectively. If both are opened together, the tank fills in:",
    options: ["48/7 hours", "7 hours", "8 hours", "9 hours"],
    answer: "A",
    correctAnswer: "48/7 hours",
    solution: "Combined rate = 1/12 + 1/16 = 7/48. Time = 48/7 hours.",
    shortcut: "Together time = xy/(x+y)."
  },
  {
    id: "AS-U2-C-17",
    unit: 2,
    category: "Concept MCQ",
    topic: "Inlet and Outlet",
    question: "A pipe fills a tank in 10 hours and another pipe empties it in 15 hours. If both are opened together, the tank will be filled in:",
    options: ["20 hours", "25 hours", "30 hours", "35 hours"],
    answer: "C",
    correctAnswer: "30 hours",
    solution: "Net filling rate = 1/10 - 1/15 = 1/30. Time = 30 hours.",
    shortcut: "If filler is faster than outlet, time = 1/(1/x - 1/y)."
  },
  {
    id: "AS-U2-C-18",
    unit: 2,
    category: "Concept MCQ",
    topic: "Three Pipes",
    question: "Pipe A fills a tank in 6 hours, Pipe B in 8 hours, and Pipe C empties it in 24 hours. If all are opened together, the tank fills in:",
    options: ["3 hours", "4 hours", "5 hours", "6 hours"],
    answer: "B",
    correctAnswer: "4 hours",
    solution: "Net rate = 1/6 + 1/8 - 1/24 = 4/24 + 3/24 - 1/24 = 6/24 = 1/4. Time = 4 hours.",
    shortcut: "Use LCM method: 4 + 3 - 1 = 6 units/hour from capacity 24."
  },
  {
    id: "AS-U2-C-19",
    unit: 2,
    category: "Concept MCQ",
    topic: "Delayed Opening",
    question: "Pipe A fills a tank in 9 hours and Pipe B in 18 hours. A is opened first. After 2 hours, B is also opened. Total time to fill the tank is:",
    options: ["5 hours 30 minutes", "6 hours 40 minutes", "7 hours", "8 hours"],
    answer: "B",
    correctAnswer: "6 hours 40 minutes",
    solution: "A fills 2/9 in 2 hours. Remaining = 7/9. A+B rate = 1/9 + 1/18 = 1/6. Remaining time = (7/9) ÷ (1/6) = 14/3 hours = 4 hours 40 minutes. Total = 6 hours 40 minutes.",
    shortcut: "First pipe work + combined remaining work."
  },
  {
    id: "AS-U2-C-20",
    unit: 2,
    category: "Concept MCQ",
    topic: "Unknown Pipe",
    question: "Pipes A and B together fill a tank in 6 hours. A alone fills it in 10 hours. B alone will fill it in:",
    options: ["12 hours", "15 hours", "18 hours", "20 hours"],
    answer: "B",
    correctAnswer: "15 hours",
    solution: "B rate = 1/6 - 1/10 = 1/15. So B alone takes 15 hours.",
    shortcut: "Unknown rate = combined rate - known rate."
  },
  {
    id: "AS-U2-C-21",
    unit: 2,
    category: "Concept MCQ",
    topic: "Pipe Closing",
    question: "Pipe A fills a tank in 20 hours and Pipe B in 30 hours. Both are opened together, but B is closed after some time. The tank is full in 18 hours. After how many hours was B closed?",
    options: ["2 hours", "3 hours", "4 hours", "5 hours"],
    answer: "B",
    correctAnswer: "3 hours",
    solution: "LCM = 60. A = 3 units/hour, B = 2 units/hour. Let B work for x hours. 5x + 3(18 - x) = 60. So 2x = 6, x = 3 hours.",
    shortcut: "Use LCM capacity and equation: combined work + single work = total capacity."
  },
  {
    id: "AS-U2-C-22",
    unit: 2,
    category: "Concept MCQ",
    topic: "Alternate Working",
    question: "Pipe A fills a tank in 12 hours and Pipe B in 18 hours. If they work on alternate hours starting with A, the tank fills in:",
    options: ["14 hours", "14 1/3 hours", "15 hours", "16 hours"],
    answer: "B",
    correctAnswer: "14 1/3 hours",
    solution: "LCM = 36. A = 3 units/hour, B = 2 units/hour. In 2 hours they fill 5 units. In 14 hours they fill 35 units. Remaining = 1 unit. A fills 3 units/hour, so time = 1/3 hour. Total = 14 1/3 hours.",
    shortcut: "Find work in one alternate cycle, then handle the remaining part."
  },
  {
    id: "AS-U2-C-23",
    unit: 2,
    category: "Concept MCQ",
    topic: "Part Filled",
    question: "A pipe fills a tank in 15 hours, another fills it in 20 hours, and a leak empties it in 60 hours. If all are opened for 6 hours, what part of the tank is filled?",
    options: ["1/2", "3/5", "2/3", "4/5"],
    answer: "B",
    correctAnswer: "3/5",
    solution: "Net rate = 1/15 + 1/20 - 1/60 = 4/60 + 3/60 - 1/60 = 6/60 = 1/10. In 6 hours, work = 6/10 = 3/5.",
    shortcut: "Part filled = net rate × time."
  },
  {
    id: "AS-U2-C-24",
    unit: 2,
    category: "Concept MCQ",
    topic: "Outlet Faster Than Inlet",
    question: "Pipe A fills a tank in 9 hours and Pipe B empties it in 6 hours. If the tank is full and both are opened, the tank will empty in:",
    options: ["12 hours", "15 hours", "18 hours", "20 hours"],
    answer: "C",
    correctAnswer: "18 hours",
    solution: "Net emptying rate = 1/6 - 1/9 = 1/18. So the full tank empties in 18 hours.",
    shortcut: "When outlet is faster, net emptying rate = outlet rate - inlet rate."
  },
  {
    id: "AS-U2-C-25",
    unit: 2,
    category: "Concept MCQ",
    topic: "Two Pipes Together",
    question: "Pipe A fills a tank in 24 hours and Pipe B fills it in 36 hours. Both together will fill the tank in:",
    options: ["12 hours", "14.4 hours", "15 hours", "16 hours"],
    answer: "B",
    correctAnswer: "14.4 hours",
    solution: "Combined rate = 1/24 + 1/36 = 5/72. Time = 72/5 = 14.4 hours.",
    shortcut: "Together time = xy/(x+y)."
  },
  {
    id: "AS-U2-C-26",
    unit: 2,
    category: "Concept MCQ",
    topic: "Similar Taps",
    question: "A tap fills a tank in 4 hours. After half the tank is filled, two more similar taps are opened. Total time required is:",
    options: ["2 hours", "2 hours 40 minutes", "3 hours", "4 hours"],
    answer: "B",
    correctAnswer: "2 hours 40 minutes",
    solution: "Half tank by one tap takes 2 hours. Remaining half by 3 taps: rate = 3/4 tank/hour. Time = (1/2) ÷ (3/4) = 2/3 hour = 40 minutes. Total = 2 hours 40 minutes.",
    shortcut: "Similar taps multiply the filling rate."
  },
  {
    id: "AS-U2-C-27",
    unit: 2,
    category: "Concept MCQ",
    topic: "Similar Taps",
    question: "A tap fills a tank in 4 hours. After half the tank is filled, three more similar taps are opened. Total time required is:",
    options: ["2 hours", "2 hours 30 minutes", "3 hours", "3 hours 30 minutes"],
    answer: "B",
    correctAnswer: "2 hours 30 minutes",
    solution: "First half takes 2 hours. Then total taps = 4, so rate = 4/4 = 1 tank/hour. Remaining half takes 1/2 hour. Total = 2 hours 30 minutes.",
    shortcut: "After opening 4 similar taps, filling speed becomes 4 times."
  },
  {
    id: "AS-U2-C-28",
    unit: 2,
    category: "Concept MCQ",
    topic: "Fast and Slow Pipes",
    question: "One pipe fills a tank four times as fast as another pipe. Together they fill the tank in 36 minutes. The slower pipe alone will fill it in:",
    options: ["144 minutes", "160 minutes", "180 minutes", "200 minutes"],
    answer: "C",
    correctAnswer: "180 minutes",
    solution: "Let slower pipe rate = x. Faster pipe rate = 4x. Together = 5x = 1/36. So x = 1/180. Slower pipe takes 180 minutes.",
    shortcut: "If rates are 1:4, total rate = 5 parts."
  },
  {
    id: "AS-U2-C-29",
    unit: 2,
    category: "Concept MCQ",
    topic: "Time Difference",
    question: "Two pipes together fill a cistern in 4 hours. If used separately, B takes 6 hours more than A. A alone will fill it in:",
    options: ["6 hours", "8 hours", "10 hours", "12 hours"],
    answer: "A",
    correctAnswer: "6 hours",
    solution: "Let A = x hours and B = x + 6 hours. 1/x + 1/(x+6) = 1/4. Solving gives x = 6. So A takes 6 hours.",
    shortcut: "When separate time difference is given, form rate equation."
  },
  {
    id: "AS-U2-C-30",
    unit: 2,
    category: "Concept MCQ",
    topic: "Pipe Turned Off",
    question: "Pipe A fills a cistern in 37.5 minutes and Pipe B in 45 minutes. Both are opened, but B is turned off after some time. The cistern fills in 30 minutes. When was B turned off?",
    options: ["5 minutes", "9 minutes", "10 minutes", "15 minutes"],
    answer: "B",
    correctAnswer: "9 minutes",
    solution: "A works for 30 minutes and fills 30/37.5 = 4/5 of tank. Remaining = 1/5. B fills 1/5 tank in 45 × 1/5 = 9 minutes.",
    shortcut: "Work left by A must be completed by B."
  },
  {
    id: "AS-U2-C-31",
    unit: 2,
    category: "Concept MCQ",
    topic: "Leak",
    question: "A pump fills a tank in 2 hours. Due to a leak, it takes 8/3 hours to fill the tank. The leak alone can empty the full tank in:",
    options: ["6 hours", "8 hours", "9 hours", "10 hours"],
    answer: "B",
    correctAnswer: "8 hours",
    solution: "Pump rate = 1/2. Actual net rate = 1/(8/3) = 3/8. Leak rate = 1/2 - 3/8 = 1/8. So leak empties in 8 hours.",
    shortcut: "Leak rate = original filling rate - reduced net filling rate."
  },
  {
    id: "AS-U2-C-32",
    unit: 2,
    category: "Concept MCQ",
    topic: "Delayed Leak",
    question: "Pipe A fills a tank in 8 hours and Pipe B in 12 hours. A and B are opened together. After 2 hours, a leak that empties the tank in 24 hours starts. Total time to fill the tank is:",
    options: ["5 hours", "5.5 hours", "6 hours", "6.5 hours"],
    answer: "B",
    correctAnswer: "5.5 hours",
    solution: "A+B rate = 1/8 + 1/12 = 5/24. Work in 2 hours = 10/24 = 5/12. Remaining = 7/12. After leak starts, net rate = 1/8 + 1/12 - 1/24 = 1/6. Remaining time = (7/12) ÷ (1/6) = 3.5 hours. Total = 5.5 hours.",
    shortcut: "Separate the work before and after leak starts."
  },
  {
    id: "AS-U2-C-33",
    unit: 2,
    category: "Concept MCQ",
    topic: "Partially Filled Tank",
    question: "A tank is 1/3 full. Pipe A fills it in 10 hours and a leak empties it in 15 hours. If both are opened, the tank will become full in:",
    options: ["15 hours", "18 hours", "20 hours", "25 hours"],
    answer: "C",
    correctAnswer: "20 hours",
    solution: "Net filling rate = 1/10 - 1/15 = 1/30. Remaining tank = 2/3. Time = (2/3) ÷ (1/30) = 20 hours.",
    shortcut: "Use remaining part ÷ net filling rate."
  },
  {
    id: "AS-U2-C-34",
    unit: 2,
    category: "Concept MCQ",
    topic: "Leak Time",
    question: "Pipes A and B fill a tank in 10 hours and 15 hours respectively. With a leak, they fill it in 12 hours. The leak alone can empty the tank in:",
    options: ["10 hours", "12 hours", "15 hours", "20 hours"],
    answer: "B",
    correctAnswer: "12 hours",
    solution: "A+B rate = 1/10 + 1/15 = 1/6. Net rate with leak = 1/12. Leak rate = 1/6 - 1/12 = 1/12. Hence leak empties in 12 hours.",
    shortcut: "Leak rate = normal combined rate - actual combined rate."
  },
  {
    id: "AS-U2-C-35",
    unit: 2,
    category: "Concept MCQ",
    topic: "Capacity",
    question: "A pipe fills a tank at 5 litres/minute. The tank capacity is 900 litres. How long will the pipe take to fill the tank?",
    options: ["2 hours", "2.5 hours", "3 hours", "3.5 hours"],
    answer: "C",
    correctAnswer: "3 hours",
    solution: "Time = Capacity / Rate = 900/5 = 180 minutes = 3 hours.",
    shortcut: "Time = Capacity ÷ filling rate."
  },

  // =====================
  // 10 TRICKY EXAM MCQs
  // =====================
  {
    id: "AS-U2-T-36",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Pipe Blockage",
    question: "Pipes A, B and C fill a tank in 12, 15 and 20 minutes respectively. All are opened together. After 4 minutes, A is blocked. After one more minute, B is also blocked. C continues till the tank is full. Total time taken is:",
    options: ["6 minutes", "6 minutes 15 seconds", "6 minutes 40 seconds", "6 minutes 50 seconds"],
    answer: "C",
    correctAnswer: "6 minutes 40 seconds",
    solution: "LCM = 60. A = 5, B = 4, C = 3 units/min. First 4 minutes: 12×4 = 48 units. Next 1 minute: B+C = 7 units, total = 55. Remaining = 5 units. C takes 5/3 minutes = 1 minute 40 seconds. Total = 6 minutes 40 seconds.",
    shortcut: "Use phase-wise work: all pipes, then remaining pipes, then last pipe."
  },
  {
    id: "AS-U2-T-37",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Sequential Closing",
    question: "Three pipes A, B and C fill a tank in 10, 20 and 30 hours respectively. All work together for x hours. Then A is closed. After 2 more hours, B is closed. C works for 14 more hours and fills the tank. Find x.",
    options: ["1 hour", "1.5 hours", "2 hours", "3 hours"],
    answer: "C",
    correctAnswer: "2 hours",
    solution: "All three rate = 1/10 + 1/20 + 1/30 = 11/60. B+C rate = 1/20 + 1/30 = 5/60. C rate = 1/30. Equation: x(11/60) + 2(5/60) + 14(1/30) = 1. Solving gives x = 2.",
    shortcut: "Make one equation using each time phase."
  },
  {
    id: "AS-U2-T-38",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Alternate Hours",
    question: "Pipe A fills a tank in 9 hours and Pipe B in 3 hours. They are opened on alternate hours starting with A. The tank will be full in:",
    options: ["4 hours", "5 hours", "6 hours", "7 hours"],
    answer: "B",
    correctAnswer: "5 hours",
    solution: "A rate = 1/9, B rate = 1/3. In 2 hours, work = 1/9 + 1/3 = 4/9. In 4 hours, work = 8/9. Remaining = 1/9, which A fills in 1 hour. Total = 5 hours.",
    shortcut: "Check remaining work after complete alternate cycles."
  },
  {
    id: "AS-U2-T-39",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Fast Pipe Ratio",
    question: "One pipe fills a tank 6 times as fast as another pipe. Together they fill the tank in 22 minutes. The slower pipe alone will fill the tank in:",
    options: ["144 minutes", "154 minutes", "164 minutes", "176 minutes"],
    answer: "B",
    correctAnswer: "154 minutes",
    solution: "Let slower rate = x. Faster rate = 6x. Together = 7x = 1/22. So x = 1/154. Slower pipe takes 154 minutes.",
    shortcut: "If speed ratio is 1:6, total rate = 7 parts."
  },
  {
    id: "AS-U2-T-40",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Square Root Formula",
    question: "Pipe A alone takes 9 hours more than A+B together. Pipe B alone takes 6.25 hours more than A+B together. How much time do A and B together take?",
    options: ["6 hours", "6.5 hours", "7 hours", "7.5 hours"],
    answer: "D",
    correctAnswer: "7.5 hours",
    solution: "If A alone takes a hours more and B alone takes b hours more than together time, then together time = √ab. So time = √(9 × 6.25) = √56.25 = 7.5 hours.",
    shortcut: "Together time = √(extra time of A × extra time of B)."
  },
  {
    id: "AS-U2-T-41",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "One Pipe Closed",
    question: "Pipes A and B fill a tank in 8 minutes and 14 minutes respectively. Both are opened together, but A is closed after 3 minutes. How much more time will B take to fill the tank?",
    options: ["6 minutes 15 seconds", "5 minutes 45 seconds", "5 minutes 15 seconds", "6 minutes 30 seconds"],
    answer: "B",
    correctAnswer: "5 minutes 45 seconds",
    solution: "LCM = 56. A = 7 units/min, B = 4 units/min. In 3 minutes, work = 11×3 = 33 units. Remaining = 23 units. B takes 23/4 = 5.75 minutes = 5 minutes 45 seconds.",
    shortcut: "Remaining work ÷ efficiency of the pipe still open."
  },
  {
    id: "AS-U2-T-42",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Pipe Turned Off",
    question: "Pipe A fills a tank in 15 minutes and Pipe B in 40 minutes. Both are opened together, but after 4 minutes A is turned off. What is the total time required to fill the tank?",
    options: ["20 minutes 10 seconds", "25 minutes 20 seconds", "29 minutes 20 seconds", "30 minutes"],
    answer: "C",
    correctAnswer: "29 minutes 20 seconds",
    solution: "In 4 minutes, work done = 4(1/15 + 1/40) = 4 × 11/120 = 11/30. Remaining = 19/30. B alone takes (19/30) × 40 = 76/3 minutes = 25 minutes 20 seconds. Total = 29 minutes 20 seconds.",
    shortcut: "Total time = initial combined time + remaining time by single pipe."
  },
  {
    id: "AS-U2-T-43",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "C Closed After Work",
    question: "Pipes A, B and C fill a tank in 12, 15 and 20 hours respectively. They work together for 2 hours, then C is closed. How much more time will A and B take to fill the remaining tank?",
    options: ["3 hours", "4 hours", "5 hours", "6 hours"],
    answer: "B",
    correctAnswer: "4 hours",
    solution: "A+B+C rate = 1/12 + 1/15 + 1/20 = 1/5. Work in 2 hours = 2/5. Remaining = 3/5. A+B rate = 1/12 + 1/15 = 3/20. Time = (3/5) ÷ (3/20) = 4 hours.",
    shortcut: "Remaining time = remaining work ÷ rate of pipes still working."
  },
  {
    id: "AS-U2-T-44",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Tank Capacity",
    question: "Pipe A alone can empty a tank in 20 hours. Pipe B drains 20 litres per hour. Together they empty the tank in 12 hours. Find the tank capacity.",
    options: ["400 litres", "500 litres", "600 litres", "800 litres"],
    answer: "C",
    correctAnswer: "600 litres",
    solution: "Let capacity = C litres. A drains C/20 litres/hour. Together: C/20 + 20 = C/12. So 20 = C/12 - C/20 = C/30. Hence C = 600 litres.",
    shortcut: "When one pipe is in litres/hour, convert all rates into litres/hour."
  },
  {
    id: "AS-U2-T-45",
    unit: 2,
    category: "Tricky Exam MCQ",
    topic: "Fractional Filling and Emptying",
    question: "Pipe A fills 1/3 of a tank in 5 minutes. Pipe B empties 1/4 of the tank in 8 minutes. If the tank is empty and both are opened, the tank will be filled in:",
    options: ["480/17 minutes", "240/17 minutes", "120/17 minutes", "60/17 minutes"],
    answer: "A",
    correctAnswer: "480/17 minutes",
    solution: "A fills full tank in 15 minutes, so A rate = 1/15. B empties full tank in 32 minutes, so B rate = 1/32. Net rate = 1/15 - 1/32 = 17/480. Time = 480/17 minutes.",
    shortcut: "First convert fractional work into full tank time, then subtract outlet rate."
  }
];

window.analyticalUnit2MCQs = analyticalUnit2MCQs;
